---
title: "Statistical Learning to Predict Firms Extortion"
author: "Pedro Armengol"
date: "June 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
Abstract
\end{center}
.5

## Introduction
A firm, as a person, can be victim of several types of crimes. As a person, a firm can be more or less prone to be victimized depending on its characteristics. Where is the firm located, what it produce, how much it sells, how old is it, profitability margin and so. All their characteristics together made of every firm a unique profit generating entity that represent an opportunity for rent extraction (**Paper 1**, **Paper 2**). 

Extracting rents through exploiting a competitive advantage in violence, say through treats, is usually call extortion; a similar concept to black mailing but involving the use of violence in order to obtain the rents from firms or persons. 

In order to participate in extortion industry, rent-seekers/ criminals make a trade-off assesment between profitability and risk before demanding for a ransom: how dangerous is to proceed vs. how much resources can they obtain from proceeding. Putting in Gary Becker terms, the trade-off of extorting a firm can be expressed as

$\Pi_{h,i} = (E(Profitability|Extortion)_{i} - E(Punishment)_{j}*Pr(Caught)_{h,j}$    (1)

Such that the expected profits for criminal or criminal group $h$ for extortion firm $i$ is equal to the expected profit of extorting firm $i$ minus the expected punishment in region ${j}$ multiply by the probability of criminal $h$ to be caught in region ${j}$. 

In some contries the trade-off turns to be alarming positive (**Paper 3**). Where the victimization rate can be as high as XX percent of the firms [^1]. It is expectable to have a particular big underreported number of this type of crime given the modus operandi of extortioneers: treat the victimis to stay in silence or suffer the consequences. Likely, extortions could impose a psicological stress burden to the firms managment and employees as well as increase the financial and/or operationas costs: such that the capacity of a firm to sustain the same levels of competence could be dramatically limited by this type of victimization.

This study uses statistical learning to model the $E(Profitability|Extortion)$ and $Pr(Caught)$ of model (1). Such that, through the use of Survey victimization data merge with census firms data, in the context for Mexico, we are able to predict for which firms $i$ the likelihood of being extorted is the bigger. Where $E(Profitability|Extortion)$ is model using the characteristics of the extorted and $Pr(Caught)$ is modeled with the locations of the firms: variations in the geographical location of the firms explain different rule of law, cultural acceptance of extortion and presence of organice crime groups (the natural candidates to commit extortions).

An extrapolation of the results is done for a whole country, Mexico, using model weights obtained through victimation survey samples and census data for the whole universe. Lastly, further extensions of this research and short-term applications of the same are discussed. 

This paper is divided in four reamining sections: Data, explains the type of statistical projects that this research uses and show some descriptive statistics. Empirical strategy and results, dicuss the prediction techniques, the structure of the results and accuracy of the predictions. Policy applications are the short-term uses of the obtained results. Further research discuss subsequent extensions of this project and, lastly, conclusion, concludes.

## Data

This project will use the economic census and victimizations surveys (both described below) to fit the likelihood that a firm will be victimized base on its chatacteristics and location. The victimization surveys will tell us if a firm was victimized for a sample of around 33 thousend firms that are representative of the universe of firms (around 4.5 million firms). Such that for a sample, we hace information of which types of crimes the firm suffered during the previous and actual year as prevalence and incidence. By the other side, for the universe, we have information of size, age, incomes, expenses, profits and so on; where the universe of the census includes the sample of the victimization survey. 

The available data about this problem makes of its solution an "state of the art" statistical learning implementation, where there is a labeled column of victimization (including victimization by extrotion) and more than hundred features of the firm recorded on the census (both sources of information are merged through a firm ID). 

### Victimization Survey (firms)

The firms victimization survey (ENVE for it's acronym in Spanish) is a tool developed by INEGI to understand the impact of the crime over the private sector (firms). The survey covers the owners insecurity perception, the most common crimes that the firms face, the crimes characteristics as well as the costs related to those. This survey has validity for all the economic units (every physical place where an economic activity is realized). The sampling was done with two criteria: size of the firm and State: the two representative stratums[^4]. The sample is composed of 33,866 firms (from a universe of 4.5 millions: taking as sampling frame the economic census of 2009). There are victimization surveys for the years 2012,2014 and 2016. A new victimization survey is coming in 2018.

The table has 156 variables related to the following categories:

- Level of victimization
- Characteristics of the crime
- Report of the crime
- Perception of insecurity
- Institutional performance
- Cost of crimes
- Cost of informal commerce and vandalism

### Economic Census

Every 5 years the Statistics Ministry of Mexico (INEGI) perform a census about the economic activity at firm unit. The outcome of the census is a table with a great level of detail in the geographical position, type of economic activity and size of the firm. The last public census was made on 2014 and covered 5.6m firms (obtaining information about 2013). The next economic census is coming the next year (2018).INEGI use the North American Industry Classification System (NAICS) for the type of economic activity label (2017 NAICS Manual is available in the folder: codebooks). 

The table has 96 variables related to the following categories:

- Geo-location 
- Type of Economic Activity (NAICS)
- Accounts (Total production, Intermediate consumption, Aggregate value, Capital formation, etc.)
- Number of employees and worked hours by gender and type (owner, direct employee, employee without constant wage, etc.)
- Wages
- Expenditures (inputs, gasoline, light, water, etc.)
- Income (goods production, goods reselling, services, renting property, etc.)
- Inventory: finished goods, goods in process, assets by type:estate, furniture, transport, etc.)

### Descriptive Analysis

From the victimization survey variables related to extortion where selected the variable described in **Table 1**. 

$Table1$

In **Table 2** are described basic statistics of the **Table 1** variables, where the means are presented for the incidence variables (firm was victimice or not) and the mean and standard desviation is presented for the prevalence variables (how many times the firm was victimized). The number of missing values in the sample is reported as well.

$Table2$

In **Table 3** Annex, the mean, standard desviation and number of missing values is presented for each variable of the census: the firms information.

## Empirical Strategy and results
In this section we describe how we model with the victimization survey of 2016 and the census of 2014 the likelihood of victimization of a firm. Also we described how the predicitons where extraplolated with the

### Modeling



### Extrapolation

# Linear regression (lm)
# Penalized Logistic Regression (plr)
# Regularized Logistic Regression(regLogistic)
# Least Squares Support Vector Machine with Polynomial Kernel (lssvmPoly)
# Gradient Boosting Machines (gbm_h2o)
# Random Forest (rf)
# CART (rpart)

## Policy Applications
1
## Further research
1
## Conclusion
.5

## Anex

$Table 3   here$

[^1]: victimization rate: the case of Mexico
[^2]: cost of extortions: case of Mexico
[^3]: The access to this data (at firm level) has to be done remotely through the Micro-data laboratory of the INEGI.
[^4]: Taking in consideration the following parameters (confidence level: 95%, relative error 13% and non-response rate 15%)


**Table 1**: Description of variables
Name: description
**Table 2** Summary of variables
Name: mean: NAs Categorical
Name: mean: Standard Desviation. NAs continuos 
**Table 3** 
Name: mean: Standard Desviation. NAs continuous
